services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports: ["8000:8000"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports: ["8501:8501"]
    environment:
      - API_URL=http://api:8000
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    ports: ["5000:5000"]
    volumes: ["./mlruns:/mlruns"]
